import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { test, expect } from "./fixtures";
import { journey } from "./journeys";

test("GitHub consent, exact repository evidence, disconnect and re-verification", journey("github-connection"), async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  await page.goto("/setup/github");
  await page.getByRole("button", { name: "Disconnect", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Disconnect", exact: true }).click();
  await expect(page.getByRole("button", { name: "Use existing login", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("github-choose.png"), fullPage: true });
  expect((await (await page.request.get("/api/github/setup")).json()).connection).toBeNull();
  await page.goto("/applications/new");
  await page.getByLabel("GitHub repository", { exact: true }).fill("https://github.com/qa/github-consent");
  await expect(page.getByRole("button", { name: "Add application", exact: true })).toBeDisabled();
  await page.getByRole("link", { name: "Connect GitHub", exact: true }).click();
  await page.getByRole("button", { name: "Use existing login", exact: true }).click();
  await expect(page.getByText("Connected as qa-fixture-user", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Choose repositories on GitHub" })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("github-connected.png"), fullPage: true });
  await page.getByRole("link", { name: "Back to add application" }).click();
  await page.getByLabel("GitHub repository", { exact: true }).fill("https://github.com/qa/github-consent");
  await page.getByRole("button", { name: "Add application", exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/[\da-f-]{36}$/, { timeout: 30_000 });
  const path = new URL(page.url()).pathname;
  const before = await (await page.request.get(`/api${path}`)).json();
  expect(before.observations[0].raw).toMatchObject({ accountId: 42, repositoryId: 99, credentialSource: "gh", accountRepositoryPermissions: { pull: true }, connectionId: expect.any(String) });
  expect(before.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("passed");
  await page.goto("/setup/github");
  await page.getByRole("button", { name: "Storage & privacy" }).click();
  await expect(page.getByRole("heading", { name: "Storage & privacy" })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "Disconnect", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Disconnect", exact: true }).click();
  await expect(page.getByRole("button", { name: "Use existing login" })).toBeVisible();
  const disconnected = await (await page.request.get(`/api${path}`)).json();
  expect(disconnected.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("not-yet");
  expect(disconnected.messages).toEqual(before.messages);
  await page.getByRole("button", { name: "Use existing login" }).click();
  await expect(page.getByText("Connected as qa-fixture-user")).toBeVisible();
  const reconnected = await (await page.request.get(`/api${path}`)).json();
  expect(reconnected.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("not-yet");
  expect((await page.request.post(`/api${path}/checks/repository-readable/rerun`, { data: {} })).ok()).toBe(true);
  const refreshed = await (await page.request.get(`/api${path}`)).json();
  expect(refreshed.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("passed");
});

test("GitHub device login cancellation, denied authorization and successful replacement", journey("github-connection"), async ({ page, fixture }, testInfo) => {
  const scenario = (value: object) => writeFileSync(join(fixture.state, "github-scenario.json"), JSON.stringify(value));
  scenario({ login: "pending" });
  await page.goto("/setup/github");
  const before = (await (await page.request.get("/api/github/setup")).json()).connection;
  await page.getByRole("button", { name: "Change", exact: true }).click();
  await page.getByRole("button", { name: "Connect another account" }).click();
  await expect(page.getByText("ABCD-1234", { exact: true })).toBeVisible();
  await expect(page.getByText("Using qa-fixture-user until the new sign-in succeeds.", { exact: true })).toBeVisible();
  await expect(page.getByRole("status").filter({ hasText: "Waiting for sign-in" })).toHaveText("Waiting for sign-in…");
  await expect(page.getByText(/^Code expires in/)).toBeVisible();
  await expect(page.getByText(/^Code expires in/)).toHaveAttribute("aria-live", "off");
  await page.screenshot({ path: testInfo.outputPath("github-device-code.png"), fullPage: true });
  await page.getByRole("button", { name: "Cancel sign-in" }).click();
  expect((await (await page.request.get("/api/github/setup")).json()).connection).toEqual(before);
  scenario({ login: "denied" });
  await page.getByRole("button", { name: "Connect another account" }).click();
  await expect(page.getByRole("alert").filter({ hasText: "GitHub sign-in was cancelled." })).toBeVisible();
  expect((await (await page.request.get("/api/github/setup")).json()).connection).toEqual(before);
  scenario({ login: "success" });
  await page.getByRole("button", { name: "Connect another account" }).click();
  await expect(page.getByText("Separate login for Server Guy", { exact: true })).toBeVisible();
  const after = (await (await page.request.get("/api/github/setup")).json()).connection;
  expect(after.mode).toBe("app"); expect(after.id).not.toBe(before.id);
  await expect(page.getByRole("link", { name: "Choose repositories on GitHub" })).toHaveAttribute("href", "https://github.com/apps/qa-server-guy/installations/new");
  await page.setViewportSize({ width: 1394, height: 1354 });
  await page.screenshot({ path: testInfo.outputPath("github-app-user-desktop.png"), fullPage: true });
});

test("GitHub repository permission denial remains an unmet check and can recover", journey("github-connection"), async ({ page, fixture }) => {
  await page.goto("/setup/github");
  await page.getByRole("button", { name: "Change", exact: true }).click();
  await page.getByRole("button", { name: "Connect another account" }).click();
  await expect(page.getByText("Separate login for Server Guy", { exact: true })).toBeVisible();
  writeFileSync(join(fixture.state, "github-scenario.json"), JSON.stringify({ repository: "missing-scope" }));
  await page.goto("/applications/new");
  await page.getByLabel("GitHub repository", { exact: true }).fill("https://github.com/qa/github-permissions");
  await page.getByRole("button", { name: "Add application", exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/[\da-f-]{36}$/);
  const path = new URL(page.url()).pathname;
  const failed = await (await page.request.get(`/api${path}`)).json();
  expect(failed.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("blocked");
  expect(failed.observations[0].summary).toContain("read access");
  writeFileSync(join(fixture.state, "github-scenario.json"), "{}");
  await page.request.post(`/api${path}/checks/repository-readable/rerun`, { data: {} });
  const passed = await (await page.request.get(`/api${path}`)).json();
  expect(passed.checks.find((check: { key: string }) => check.key === "repository-readable").status).toBe("passed");
  expect(passed.observations[0].raw.installationId).toBe(7);
});
