export const phases = [
  { id: 1, short: "Start", name: "Start", deliverable: "Launch Brief", outcome: "A durable brief for this application and launch.", meaning: "The application identity, repository, target environment, authority mode, and operating priorities Pi should preserve throughout launch.", source: "Journey 01 · Phase 1 · Launch Brief", takeover: "Launch Brief in the Operator Record or its originating chat", gate: ["Application identity recorded", "Repository readable", "Environment, authority, and intent explicit"], exit: "Launch Brief gate passed" },
  { id: 2, short: "Understand", name: "Understand", deliverable: "Application Contract", outcome: "A source-attributed contract with a resolved profile match or gap.", meaning: "The operational agreement for how this application is built, configured, checked, observed, migrated, backed up, and verified—with provenance for every material field.", source: "Journey 01 · Phase 2 · Application Contract", takeover: "Repository runtime/configuration, server-guy.yaml, or a user-confirmed contract field", gate: ["Profile match or explicit mismatch recorded", "Material fields carry provenance", "Unknowns resolved or named as blockers"], exit: "Application Contract gate passed" },
  { id: 3, short: "Conform", name: "Conform", deliverable: "Conformance Result", outcome: "An exact repository revision eligible for launch.", meaning: "The evidence that one exact repository revision now satisfies the supported Application Profile, with every remaining gap named.", source: "Journey 01 · Phase 3 · Conformance Result", takeover: "The conformance pull request, repository code, or operational configuration", gate: ["Required changes merged", "Exact revision passes profile checks", "No required conformance gap remains"], exit: "Conformance Result gate passed" },
  { id: 4, short: "See launch", name: "See the launch", deliverable: "Launch Plan", outcome: "A credible plan the engineer can inspect before creation.", meaning: "The intended topology, cost, responsibilities, verification, and material risks before any paid infrastructure is created.", source: "Journey 01 · Phase 4 · Launch Plan", takeover: "Launch Plan choices in the Operator Record", gate: ["Topology and cost explicit", "Provider and engineer actions separated", "Verification and material risks named"], exit: "Launch Plan gate passed" },
  { id: 5, short: "VPS", name: "Establish the VPS", deliverable: "Host Record", outcome: "An owned host with identity, cost, and readiness evidence.", meaning: "The durable identity, actual cost, configuration target, and readiness evidence for the user-owned host.", source: "Journey 01 · Phase 5 · Host Record", takeover: "Hetzner host configuration or the proposed host operation", gate: ["Intended host exists", "Identity and actual cost recorded", "Host readiness checks pass"], exit: "Host Record gate passed" },
  { id: 6, short: "Domain", name: "Establish the domain", deliverable: "Domain Route", outcome: "An authoritative HTTPS route observed from outside the host.", meaning: "The intended hostname, authoritative DNS route, valid HTTPS, and external observations proving that the public route is established.", source: "Journey 01 · Phase 6 · Domain Route", takeover: "Cloudflare DNS, registrar nameservers, or the intended hostname decision", gate: ["Domain control observed", "Intended DNS and HTTPS observed externally", "No unresolved conflict or propagation wait"], exit: "Domain Route gate passed" },
  { id: 7, short: "Operations", name: "Establish operations", deliverable: "Operational Baseline", outcome: "A release-ready environment with operational evidence.", meaning: "The minimum runtime, database, secrets, backup, logs, telemetry, and external observation responsibilities required for this launch.", source: "Journey 01 · Phase 7 · Operational Baseline", takeover: "Host services, backup/log/telemetry configuration, or the accepted baseline decision", gate: ["Required responsibilities explicit", "Required services ready", "Evidence channels reporting"], exit: "Operational Baseline gate passed" },
  { id: 8, short: "Go live", name: "Go live", deliverable: "Verified Release", outcome: "An exact candidate supported as live by public checks.", meaning: "The exact revision and deployment configuration currently supported as live by contract and semantic checks through the intended public route.", source: "Journey 01 · Phase 8 · Verified Release", takeover: "Release candidate, deployment configuration, or failing application check", gate: ["Exact candidate deployed", "Public contract checks pass", "Semantic checks pass and Release is current"], exit: "Verified Release gate passed" },
  { id: 9, short: "Handoff", name: "Handoff", deliverable: "Operations Handoff", outcome: "A complete launch record that enters ongoing operations.", meaning: "The launch evidence, remaining gaps, ownership, and active observation path needed to operate the application after launch.", source: "Journey 01 · Phase 9 · Operations Handoff", takeover: "Launch evidence, accepted gaps, ownership, or ongoing observation settings", gate: ["Launch evidence assembled", "Gaps and ownership visible", "Ongoing observation active"], exit: "Operations Handoff gate passed" },
];

export const gateProgressByState = {
  "L1.1": 0, "L1.2": 1, "L1.3": 3,
  "L2.1": 1, "L2.2": 2, "L2.3": 3,
  "L3.1": 0, "L3.2": 2, "L3.3": 3,
  "L4.1": 1, "L4.2": 2, "L4.3": 3,
  "L5.1": 0, "L5.2": 1, "L5.3": 2, "L5.4": 3,
  "L6.1": 0, "L6.2": 1, "L6.3": 1, "L6.4": 0, "L6.5": 1, "L6.6": 1, "L6.7": 2, "L6.8": 3,
  "L7.1": 0, "L7.2": 1, "L7.3": 1, "L7.4": 3,
  "L8.1": 0, "L8.2": 1, "L8.3": 1, "L8.4": 1, "L8.5": 3,
  "L9.1": 1, "L9.2": 2, "L9.3": 3,
};

const state = (config) => ({
  tone: "progress",
  facts: [],
  groups: [],
  events: [],
  quickActions: ["Explain this state", "Show evidence"],
  secondary: "Pause launch",
  ...config,
});

export const journeyStates = [
  state({
    id: "L1.1", phase: 1, name: "Start launch", status: "Needs input",
    objective: "Create an application workspace with explicit intent and authority.",
    summary: "Select the repository and production target, then tell Pi what matters before it inspects or changes anything.",
    facts: [["Repository", "Select a GitHub repository", "Required"], ["Environment", "Production", "User-selected"], ["Approval Mode", "Pi Decides", "User-selected"], ["Operating intent", "Cost-sensitive · database data matters", "Engineer brief"]],
    groups: [{ title: "Launch inputs", items: [["Repository access", "Read-only inspection begins automatically", "ready"], ["Paid infrastructure", "No resource creation is authorized yet", "locked"], ["Domain starting state", "Already owned or needs acquisition", "unknown"]] }],
    intent: "I need the repository, target environment, and your operating priorities before I can form a launch contract.",
    pi: "I can begin with read-only repository inspection. Choosing Pi Decides does not itself authorize a VPS or domain purchase.",
    question: "Use Production, Pi Decides, and keep the first launch cost-sensitive—but do not risk the database.",
    events: [["Workspace draft created", "No external state changed", "recorded"]],
    primary: "Create application workspace",
    source: "Journey phase 1 · Starting state",
  }),
  state({
    id: "L1.2", phase: 1, name: "Prerequisites visible", status: "Needs input", tone: "warning",
    objective: "Expose missing access without blocking safe inspection.",
    summary: "Server Guy distinguishes what is available, what is missing, and what can proceed now.",
    facts: [["GitHub", "Connected · northstar repository readable", "Observed"], ["Hetzner", "Not connected", "Missing"], ["Cloudflare", "Connected · account readable", "Observed"], ["Domain", "Ownership path not chosen", "Unknown"]],
    groups: [{ title: "What can happen now", items: [["Inspect repository", "Safe to begin read-only", "ready"], ["Plan infrastructure", "Can draft without creating resources", "ready"], ["Provision VPS", "Requires Hetzner access later", "blocked"]] }],
    intent: "I will inspect the repository now and ask for Hetzner access only when the VPS operation becomes current.",
    pi: "Hetzner is missing, but that should not stop contract discovery. We can defer it until phase 5.",
    events: [["Validated GitHub access", "Repository metadata and default branch readable", "passed"], ["Checked provider prerequisites", "Hetzner credential not present", "attention"]],
    primary: "Begin repository inspection", secondary: "Connect Hetzner now",
    source: "Starting state · Alternate path: provider step blocks automation",
  }),
  state({
    id: "L1.3", phase: 1, name: "Workspace created", status: "Complete", tone: "success",
    objective: "Hand a durable, explicit application context to inspection.",
    summary: "The application identity, authority mode, environment, and operating intent are now durable.",
    facts: [["Application", "northstar", "User-confirmed"], ["Repository", "github.com/lyubomir/northstar", "Repository-declared"], ["Environment", "Production", "User-confirmed"], ["Operator Session", "launch_01J...7A", "Recorded"]],
    groups: [{ title: "Authority context", items: [["Read-only inspection", "May proceed automatically", "allowed"], ["State-changing work", "Follows Pi Decides mode", "bounded"], ["Future permission", "No approval has been granted", "none"]] }],
    intent: "Next I will inspect the repository and draft a contract with provenance for every material field.",
    pi: "The workspace is durable. If your laptop stops, the session can resume from this state.",
    events: [["Operator Session recorded", "Application identity and intent persisted", "recorded"]],
    primary: "Continue to Understand", source: "Journey phase 1 exit",
  }),

  state({
    id: "L2.1", phase: 2, name: "Repository inspection", status: "Inspecting",
    objective: "Understand the application without presenting hypotheses as facts.",
    summary: "Pi inspects the repository while the Operator View separates evidence, inference, and unknowns.",
    facts: [["Runtime", "Next.js 16", "Repository-declared"], ["Database", "PostgreSQL", "Inferred"], ["Package manager", "pnpm", "Repository-declared"], ["Health endpoint", "Not found", "Observed"]],
    groups: [{ title: "Inspection queue", items: [["Read manifests", "package.json · lockfile · Docker files", "passed"], ["Find runtime boundaries", "web process and database dependency", "active"], ["Resolve secrets", "Names known; values never read from Git", "pending"]] }],
    intent: "I am testing whether this repository matches the supported Next.js + PostgreSQL profile.",
    pi: "My PostgreSQL conclusion is still inferred from imports and environment names. Correct me if the production database differs.",
    question: "PostgreSQL is correct. The app also runs background email jobs.",
    events: [["Read repository manifests", "42 files inspected", "passed"], ["Searched health contract", "No supported endpoint found", "attention"]],
    primary: "Record correction", secondary: "Let inspection continue",
    source: "Journey phase 2 · Operator UI provenance requirements",
  }),
  state({
    id: "L2.2", phase: 2, name: "Application Contract review", status: "Needs input",
    objective: "Make the proposed contract and its provenance inspectable.",
    summary: "The contract is credible enough to review, but unknowns remain visible and Pi confidence does not erase them.",
    facts: [["Profile", "Next.js + PostgreSQL", "Matched"], ["Web command", "pnpm start", "Repository-declared"], ["Health path", "/api/health", "Proposed"], ["Migration command", "Unknown", "Needs input"]],
    groups: [{ title: "Contract provenance", items: [["Repository-declared", "12 fields", "stable"], ["Pi-inferred", "4 fields", "review"], ["Engineer-confirmed", "2 fields", "confirmed"], ["Unknown", "1 material field", "attention"]] }],
    intent: "I need to resolve the migration command and confirm the background worker before paid infrastructure work.",
    pi: "The web runtime matches the profile. The deployment contract is not complete until database migrations are bounded.",
    events: [["Profile resolver completed", "Next.js + PostgreSQL matched with two gaps", "recorded"]],
    primary: "Correct contract", secondary: "Accept visible unknown",
    decision: "Workshop choice: must this contract be explicitly confirmed before paid work in Pi Decides and Full Autonomy?",
    source: "Journey phase 2 · Consequential unresolved choice 3",
  }),
  state({
    id: "L2.3", phase: 2, name: "Profile gap or unsupported repository", status: "Blocked", tone: "danger",
    objective: "Stop before an unbounded production setup.",
    summary: "This repository does not currently satisfy a supported Application Profile.",
    facts: [["Closest profile", "Next.js + PostgreSQL", "Partial match"], ["Unsupported process", "Long-running email worker", "Observed"], ["Health contract", "Missing", "Observed"], ["Deploy eligibility", "Not eligible", "Authoritative"]],
    groups: [{ title: "Bounded paths", items: [["Conform repository", "Add supported health and worker contracts", "available"], ["Remove worker from launch", "Requires engineer confirmation", "available"], ["Improvise production setup", "Outside supported boundary", "forbidden"]] }],
    intent: "I will not call this deployable until we resolve the worker and health contract.",
    pi: "I found a worker process the current profile does not describe. I can prepare a bounded conformance proposal or stop here.",
    events: [["Profile match rejected", "Material runtime responsibility is unmodeled", "blocked"]],
    primary: "Prepare conformance plan", secondary: "Stop launch",
    source: "Alternate path: unsupported repository",
  }),

  state({
    id: "L3.1", phase: 3, name: "Conformance plan", status: "Needs input",
    objective: "Make the repository satisfy a supported launch contract.",
    summary: "Source-controlled changes are separated from operational configuration and explained before work begins.",
    facts: [["Health endpoint", "Add /api/health", "Source-controlled"], ["Structured logging", "Emit Server Guy envelope", "Source-controlled"], ["Deploy manifest", "Add server-guy.yaml", "Source-controlled"], ["Secrets", "Configure after host exists", "Operational"]],
    groups: [{ title: "Required changes", items: [["Application code", "Health endpoint and graceful shutdown", "review"], ["Operational config", "Deployment manifest and log fields", "review"], ["Provider state", "No changes in this phase", "none"]] }],
    intent: "I will prepare one reviewable repository change for the minimum conformance gaps.",
    pi: "The health endpoint requires application code. The deployment manifest and logging envelope are operational integration work.",
    events: [["Conformance analysis recorded", "Four required gaps; one deferred operation", "recorded"]],
    primary: "Prepare repository change", source: "Journey phase 3",
  }),
  state({
    id: "L3.2", phase: 3, name: "Reviewable repository change", status: "Awaiting review", tone: "warning",
    objective: "Let the engineer inspect source-controlled conformance work.",
    summary: "A bounded pull request exists before the first Release can be considered eligible.",
    facts: [["Pull request", "#42 · Make app Server Guy conformant", "GitHub"], ["Branch", "server-guy/conformance", "Recorded"], ["Files", "5 changed · +118 −6", "Observed"], ["Checks", "14 passed · 1 pending", "GitHub Actions"]],
    groups: [{ title: "Change boundary", items: [["Health endpoint", "Application code", "review"], ["Logging envelope", "Operational integration", "review"], ["Deployment manifest", "Operational configuration", "review"]] }],
    intent: "I am waiting for the repository change to be reviewed and merged; I will not bypass it with an ad hoc host edit.",
    pi: "The PR changes one application endpoint and adds operational configuration. It does not provision infrastructure.",
    events: [["Pull request prepared", "GitHub PR #42 opened", "recorded"], ["CI checks", "14 passed; smoke contract pending", "active"]],
    primary: "Open pull request", secondary: "Mark unresolved",
    source: "Journey phase 3 · Alternate path: conformance needs code",
  }),
  state({
    id: "L3.3", phase: 3, name: "Conformance outcome", status: "Complete with gaps", tone: "success",
    objective: "Record exactly what became conformant and what did not.",
    summary: "The merged revision satisfies the supported profile; one non-blocking telemetry enhancement remains explicit.",
    facts: [["Merged revision", "8c14d72", "GitHub"], ["Profile", "Next.js + PostgreSQL", "Supported"], ["Required gaps", "0", "Resolved"], ["Accepted gap", "Custom business metric absent", "Non-blocking"]],
    groups: [{ title: "Conformance evidence", items: [["Health contract", "Passed deterministic test", "passed"], ["Logging shape", "Valid sample event", "passed"], ["Deploy manifest", "Schema valid", "passed"]] }],
    intent: "The application is now eligible for a launch plan. I will carry the accepted telemetry gap forward.",
    pi: "Required conformance is complete. I have not silently converted the custom metric gap into a success.",
    events: [["Merge observed", "Revision 8c14d72 on main", "passed"], ["Contract refreshed", "All required fields resolved", "recorded"]],
    primary: "See the launch", source: "Journey phase 3 exit",
  }),

  state({
    id: "L4.1", phase: 4, name: "Launch intent review", status: "Needs input",
    objective: "Make the intended topology, cost, actions, checks, and risks understandable.",
    summary: "VPS provisioning and domain work are separate visible operations with separate participation.",
    facts: [["Topology", "Cloudflare → Hetzner VPS → Next.js + PostgreSQL", "Proposed"], ["Estimated cost", "€8.10–€12.40 / month", "Provider estimate"], ["VPS operation", "Create one Hetzner machine", "Separate"], ["Domain operation", "Delegate northstar.dev to Cloudflare", "Separate"]],
    groups: [{ title: "Launch path", items: [["Engineer", "Connect Hetzner; delegate nameservers", "required"], ["Pi", "Provision, configure, deploy, verify", "proposed"], ["Verification", "HTTPS health + semantic smoke through hostname", "required"], ["Risk", "DNS propagation may pause the launch", "visible"]] }],
    intent: "I propose one small VPS and a Cloudflare-fronted public route, with verification through northstar.dev.",
    pi: "The important trade-off is a single low-cost host versus stronger isolation. The database makes backup responsibility material.",
    events: [["Launch intent drafted", "Based on contract 8c14d72 and cost preference", "recorded"]],
    primary: "Accept launch intent", secondary: "Correct plan",
    source: "Journey phase 4 · Operator UI requirements",
  }),
  state({
    id: "L4.2", phase: 4, name: "Plan revised by evidence", status: "Needs review", tone: "warning",
    objective: "Show how new evidence changed the launch rather than quietly replacing the plan.",
    summary: "Repository inspection found a background worker, changing capacity and process supervision.",
    facts: [["Changed fact", "Background email worker is production-critical", "Engineer-confirmed"], ["Machine", "cx22 → cx32", "Revised"], ["Estimated cost", "+€5.20 / month", "Changed"], ["Runtime", "Web + worker processes", "Changed"]],
    groups: [{ title: "Plan diff", items: [["Added", "Worker process and health observation", "new"], ["Changed", "Machine memory 4 GB → 8 GB", "changed"], ["Unchanged", "Domain path and public verification", "stable"]] }],
    intent: "I adapted the host plan because the worker is part of the confirmed application contract.",
    pi: "The previous machine estimate is no longer credible. I am showing the cost increase before any paid resource exists.",
    events: [["Contract evidence changed", "Worker marked production-critical", "attention"], ["Launch intent revised", "Cost and topology diff recorded", "recorded"]],
    primary: "Accept revised intent", secondary: "Change capacity choice",
    source: "Journey phase 4: adapts as evidence changes",
  }),
  state({
    id: "L4.3", phase: 4, name: "Ready to establish infrastructure", status: "Ready", tone: "success",
    objective: "Begin with a comprehensible, bounded provider operation.",
    summary: "The launch intent is credible, and the engineer can see exactly where participation is expected.",
    facts: [["First operation", "Establish the VPS", "Next"], ["Paid resources", "One Hetzner cx32", "Not created"], ["User step later", "Nameserver delegation", "Expected"], ["Unresolved", "Operational live baseline", "Workshop decision"]],
    groups: [{ title: "Participation checklist", items: [["Hetzner access", "Connect during VPS phase", "next"], ["VPS action", "Pi Decides approval behavior", "upcoming"], ["Domain delegation", "User-owned account step", "later"]] }],
    intent: "I will establish the VPS first. I will not bundle domain work into that operation.",
    pi: "Everything paid or account-level remains visible at the moment it becomes actionable.",
    events: [["Launch intent marked credible", "No material unknown blocks infrastructure planning", "passed"]],
    primary: "Begin VPS operation", source: "Journey phase 4 exit",
  }),

  state({
    id: "L5.1", phase: 5, name: "Hetzner access", status: "Needs input",
    objective: "Validate only the provider access needed for the planned host.",
    summary: "Connection and scope are visible before Pi attempts a paid operation.",
    facts: [["Provider", "Hetzner Cloud", "Planned"], ["Connection", "Not connected", "Missing"], ["Required scope", "Read project · create server · read pricing", "Proposed"], ["Master credentials", "Not requested", "Boundary"]],
    groups: [{ title: "Access validation", items: [["Read project", "Needed to avoid duplicate resources", "required"], ["Read prices", "Needed to refresh cost", "required"], ["Create server", "Used only for the visible VPS operation", "state-changing"]] }],
    intent: "I need scoped Hetzner access to validate the plan and create the single approved host.",
    pi: "Connecting the provider does not authorize every resource. The next screen will show the exact machine and cost.",
    events: [["Hetzner connection requested", "Waiting for engineer-owned account step", "attention"]],
    primary: "Connect Hetzner", source: "Journey phase 5 · Trust behavior",
  }),
  state({
    id: "L5.2", phase: 5, name: "VPS action gate", status: "Awaiting approval", tone: "warning",
    objective: "Make the paid resource and expected effect explicit.",
    summary: "A single provider action is ready under the selected Approval Mode.",
    facts: [["Action", "Create server", "State-changing"], ["Machine", "cx32 · 8 GB · 4 vCPU", "Planned"], ["Region", "Nuremberg · eu-central", "Planned"], ["Expected cost", "€9.49 / month", "Live provider price"]],
    groups: [{ title: "Expected effect", items: [["Creates", "One Ubuntu 24.04 VPS", "paid"], ["Does not create", "Domain, DNS records, or certificates", "separate"], ["On rejection", "No provider state changes", "safe"]] }],
    intent: "This machine matches the revised launch intent. I am pausing at the separate VPS action boundary.",
    pi: "Pi Decides can approve bounded actions based on context, but the product still shows the exact paid effect before execution.",
    events: [["Provider price refreshed", "€9.49 monthly at 16:42 UTC", "observed"]],
    primary: "Approve VPS creation", secondary: "Modify machine",
    decision: "Workshop choice: exact account actions that remain user-only in Full Autonomy are not settled.",
    source: "Journey phase 5 · Product requirement: paid operations",
  }),
  state({
    id: "L5.3", phase: 5, name: "VPS provisioning", status: "Acting",
    objective: "Create the planned host and expose real provider activity.",
    summary: "The Operator View shows state transitions and provider observations instead of a generic spinner.",
    facts: [["Requested server", "northstar-prod-01", "Submitted"], ["Provider operation", "op-984233", "Hetzner"], ["Current state", "Initializing network", "Observed"], ["Elapsed", "00:46", "Local session"]],
    groups: [{ title: "Provisioning activity", items: [["Create server", "Provider accepted request", "passed"], ["Assign network", "Public IPv4 allocated", "passed"], ["Wait for running", "Server state is initializing", "active"], ["Record identity", "Pending running state", "pending"]] }],
    intent: "I am reconciling the requested machine with Hetzner until its identity and running state are observed.",
    pi: "The create request succeeded, but I will not call the host ready until Hetzner reports running and I can reach it.",
    events: [["Create server", "HTTP 201 · operation op-984233", "passed"], ["Observe server", "Status initializing", "active"]],
    primary: "View provider evidence", secondary: "Pause after current action",
    source: "Journey phase 5 behavior",
  }),
  state({
    id: "L5.4", phase: 5, name: "Owned host ready", status: "Complete", tone: "success",
    objective: "Record the owned host separately from domain work.",
    summary: "The host exists, has an observed identity and cost, and is ready for application configuration.",
    facts: [["Server", "northstar-prod-01 · 59301844", "Hetzner"], ["Public IP", "49.12.118.42", "Observed"], ["Region", "Nuremberg · eu-central", "Observed"], ["Recurring cost", "€9.49 / month", "Provider"]],
    groups: [{ title: "Readiness checks", items: [["Provider state", "Running", "passed"], ["Network reachability", "SSH port reachable", "passed"], ["Host configuration", "Not started", "next"], ["Domain work", "Not started", "separate"]] }],
    intent: "The owned host is ready. Next I will establish the intended public hostname as a separate guided operation.",
    pi: "No DNS or domain state changed while creating this machine.",
    events: [["Host identity recorded", "Server 59301844 at 49.12.118.42", "recorded"], ["Cost recorded", "€9.49 monthly", "recorded"]],
    primary: "Continue to Domain Setup", source: "Journey phase 5 exit",
  }),

  state({
    id: "L6.1", phase: 6, name: "Choose hostname and starting path", status: "Needs input",
    objective: "Establish the intended public hostname without assuming domain ownership.",
    summary: "The engineer chooses an existing-domain or acquire-domain path before Server Guy claims control.",
    facts: [["Intended hostname", "northstar.dev", "Engineer input"], ["Path A", "I already own this domain", "Available"], ["Path B", "I need to acquire a domain", "Available"], ["Cloudflare control", "Not evaluated", "Unknown"]],
    groups: [{ title: "What follows", items: [["Existing domain", "Check registrar, Cloudflare zone, and authority", "guided"], ["No domain", "Guide acquisition/addition, then resume", "user-owned"], ["Automation boundary", "DNS and HTTPS begin after control is observed", "fixed"]] }],
    intent: "I need the intended hostname and domain starting path before I can test Cloudflare control.",
    pi: "Owning the domain and Cloudflare being authoritative are separate facts. I will verify both rather than infer them.",
    events: [["Domain Setup opened", "No domain or DNS state changed", "recorded"]],
    primary: "Use an existing domain", secondary: "I need a domain",
    source: "Settled Domain Setup decisions",
  }),
  state({
    id: "L6.2", phase: 6, name: "Existing Cloudflare-controlled domain", status: "Ready",
    objective: "Confirm authority before automated DNS and HTTPS work.",
    summary: "Cloudflare is already authoritative for the zone, so the bounded operation can proceed according to Approval Mode.",
    facts: [["Hostname", "northstar.dev", "Engineer-confirmed"], ["Registrar", "Cloudflare Registrar", "Observed"], ["Zone", "northstar.dev", "Cloudflare API"], ["Authority", "Cloudflare nameservers observed", "Verified"]],
    groups: [{ title: "Planned route", items: [["DNS", "A/AAAA records to 49.12.118.42", "planned"], ["HTTPS", "Cloudflare certificate and origin route", "planned"], ["Conflict check", "No conflicting apex records", "passed"]] }],
    intent: "Control is observed. I can now configure the public route and verify it from outside the host.",
    pi: "No registrar step is required on this path. The next state-changing work follows Pi Decides mode.",
    events: [["Checked authoritative NS", "Cloudflare nameservers returned", "passed"], ["Checked zone access", "Zone readable via API", "passed"]],
    primary: "Configure route and HTTPS", source: "Journey phase 6 · Settled decisions",
  }),
  state({
    id: "L6.3", phase: 6, name: "Domain registered elsewhere", status: "Needs input", tone: "warning",
    objective: "Guide nameserver delegation and resume when Cloudflare control is observable.",
    summary: "The domain remains at Namecheap; Server Guy gives exact account instructions without pretending propagation is immediate.",
    facts: [["Hostname", "northstar.dev", "Engineer-confirmed"], ["Registrar", "Namecheap", "Observed"], ["Cloudflare zone", "Created · not authoritative", "Cloudflare API"], ["Nameserver delegation", "Required", "Blocked on engineer"]],
    groups: [{ title: "Set at Namecheap", items: [["dale.ns.cloudflare.com", "Replace current nameservers", "required"], ["lucy.ns.cloudflare.com", "Replace current nameservers", "required"], ["Other nameservers", "Remove to avoid mixed delegation", "required"]] }],
    intent: "I am waiting for you to delegate northstar.dev from Namecheap to Cloudflare.",
    pi: "After you update the nameservers, I will detect authority, configure DNS, provision HTTPS, and verify the public route.",
    question: "What exactly do I need to change?",
    events: [["Check nameservers", "Namecheap BasicDNS still authoritative", "attention"], ["Check Cloudflare zone", "Zone exists but control not observed", "attention"]],
    quickActions: ["Explain this step", "Open Namecheap guide", "Check again"],
    primary: "I've updated the nameservers", secondary: "Open Namecheap guide",
    source: "Alternate path: registered elsewhere",
  }),
  state({
    id: "L6.4", phase: 6, name: "No domain owned", status: "Needs input", tone: "warning",
    objective: "Guide acquisition without making browser-controlled checkout a V1 requirement.",
    summary: "Domain acquisition is a user-owned account step with a precise return condition.",
    facts: [["Desired domain", "northstar.dev", "Engineer choice"], ["Availability", "Not yet checked", "External account"], ["Checkout owner", "Engineer", "Boundary"], ["Resume condition", "Domain appears in Cloudflare account", "Observable"]],
    groups: [{ title: "Guided path", items: [["Choose domain", "Confirm intended production hostname", "current"], ["Acquire or add", "Complete in Cloudflare account", "user action"], ["Return", "Server Guy detects zone and control", "resumable"]] }],
    intent: "I will guide the account step and resume only after the domain is observable in your Cloudflare account.",
    pi: "Automating registrar checkout in a browser is an experimental course exercise, not a required V1 capability.",
    events: [["Acquisition path selected", "Waiting for user-owned account step", "attention"]],
    primary: "Open Cloudflare domain flow", secondary: "Choose a different hostname",
    source: "Alternate path: no domain · Outside journey boundary",
  }),
  state({
    id: "L6.5", phase: 6, name: "Waiting for control or propagation", status: "Waiting externally", tone: "warning",
    objective: "Wait without losing context or implying that work is happening.",
    summary: "The nameserver change was reported, but external observations do not yet show Cloudflare authority.",
    facts: [["Reported change", "Nameservers updated at Namecheap", "Engineer"], ["Observed NS", "Namecheap BasicDNS", "External DNS"], ["Last checked", "16:48:32 UTC", "Recorded"], ["Next automatic check", "~60 seconds", "Scheduled"]],
    groups: [{ title: "Waiting state", items: [["Server Guy changes", "None while authority is absent", "paused"], ["Resume trigger", "Cloudflare NS and SOA observed", "external"], ["Context", "Guided Operation remains durable", "recorded"]] }],
    intent: "I am re-checking DNS authority. I will not configure records or HTTPS until Cloudflare control is observed.",
    pi: "Propagation can take time. The important fact is the currently observed authority, not the registrar form submission.",
    events: [["Check authoritative NS", "Namecheap nameservers still returned", "attention"], ["Schedule next observation", "Re-check in approximately 60 seconds", "recorded"]],
    primary: "Check again now", secondary: "Pause automatic checks",
    source: "Alternate path: DNS propagation pending",
  }),
  state({
    id: "L6.6", phase: 6, name: "Existing DNS conflict", status: "Blocked", tone: "danger",
    objective: "Resolve a conflicting route without overwriting unrelated DNS.",
    summary: "An apex record already points northstar.dev to another host, so Pi presents impact and bounded choices.",
    facts: [["Conflicting record", "A northstar.dev → 203.0.113.18", "Cloudflare"], ["Planned record", "A northstar.dev → 49.12.118.42", "Launch intent"], ["Current traffic", "Existing host may be serving users", "Risk"], ["Automatic overwrite", "Not allowed", "Blocked"]],
    groups: [{ title: "Resolution choices", items: [["Replace apex", "Moves northstar.dev to the new VPS", "impact"], ["Use subdomain", "Launch at app.northstar.dev", "alternative"], ["Investigate record", "Gather origin and traffic evidence", "safe"]] }],
    intent: "I need a conscious routing decision before I change this record.",
    pi: "Overwriting the apex could interrupt an existing service. I recommend investigating the current origin first.",
    events: [["DNS conflict detected", "Existing apex differs from planned host", "blocked"]],
    primary: "Investigate current record", secondary: "Choose another hostname",
    source: "Alternate path: existing DNS conflicts",
  }),
  state({
    id: "L6.7", phase: 6, name: "Configure route and HTTPS", status: "Acting",
    objective: "Create and observe the public route after control is established.",
    summary: "DNS, certificate, propagation, and public-route checks appear as separate activities.",
    facts: [["Cloudflare control", "Observed", "External NS + API"], ["DNS target", "49.12.118.42", "Host identity"], ["HTTPS", "Provisioning", "Cloudflare"], ["Public route", "Not verified", "Authoritative"]],
    groups: [{ title: "Bounded operation", items: [["Create DNS records", "A northstar.dev → 49.12.118.42", "passed"], ["Provision HTTPS", "Certificate pending issuance", "active"], ["Observe propagation", "Two external resolvers checked", "active"], ["Verify hostname", "Waits for valid HTTPS", "pending"]] }],
    intent: "Control is established. I am configuring the intended route and will verify it from outside the host.",
    pi: "DNS write succeeded. That is not yet a verified hostname; certificate and external-route checks remain.",
    events: [["Create DNS record", "Cloudflare change cf_92a1 recorded", "passed"], ["Request certificate", "Issuance pending", "active"]],
    primary: "View live evidence", secondary: "Pause after current action",
    source: "Journey phase 6 behavior",
  }),
  state({
    id: "L6.8", phase: 6, name: "Public hostname verified", status: "Verified", tone: "success",
    objective: "Prove the intended HTTPS hostname works from outside the host.",
    summary: "Server Guy distinguishes control, DNS, HTTPS, reachability, and external verification.",
    facts: [["Hostname", "https://northstar.dev", "Intended"], ["DNS", "Resolves through Cloudflare", "Verified"], ["HTTPS", "Valid certificate · TLS 1.3", "Verified"], ["External response", "200 OK from Sofia and Frankfurt", "Observed"]],
    groups: [{ title: "Domain evidence", items: [["Authority", "Cloudflare NS and SOA", "passed"], ["Routing", "Cloudflare → 49.12.118.42", "passed"], ["TLS", "Certificate valid for northstar.dev", "passed"], ["Application semantics", "Deferred to first Release verification", "next"]] }],
    intent: "The public hostname is verified. Next I will establish the operational environment behind it.",
    pi: "The route is externally verified, but the application is not live yet because no verified Release exists.",
    events: [["External hostname check", "DNS, TLS, and HTTP route passed", "passed"]],
    primary: "Establish operations", source: "Journey phase 6 exit · Successful outcome",
  }),

  state({
    id: "L7.1", phase: 7, name: "Operational baseline scope", status: "Workshop decision", tone: "warning",
    objective: "Decide which operational responsibilities gate the first live claim.",
    summary: "All responsibilities are visible, but the minimum required baseline is intentionally unresolved in the product workshop.",
    facts: [["Runtime", "Required", "Journey requirement"], ["Database", "Required", "Journey requirement"], ["External sentinel", "Candidate live gate", "Unresolved"], ["Backup + restore", "Candidate live gate", "Unresolved"]],
    groups: [{ title: "Responsibilities", items: [["Secrets", "References and delivery", "required"], ["Backups", "Database backup and evidence", "unresolved"], ["Logs", "Structured collection", "unresolved"], ["Telemetry", "Traces and metrics", "unresolved"], ["Sentinel", "External observation", "required by successful outcome"]] }],
    intent: "I can propose a baseline, but the product owner must decide which incomplete responsibilities block the word live.",
    pi: "The journey requires ongoing external observation. The exact backup, logs, and telemetry gate is not yet settled.",
    events: [["Operational responsibilities resolved", "Eight responsibilities found; launch policy incomplete", "attention"]],
    primary: "Review proposed baseline", secondary: "Keep workshop choice open",
    decision: "Unresolved: minimum operational baseline required before Server Guy says live.",
    source: "Journey phase 7 · Consequential unresolved choice 1",
  }),
  state({
    id: "L7.2", phase: 7, name: "Establish operations", status: "Acting",
    objective: "Configure the environment while exposing inspectable activity.",
    summary: "Host, database, runtime, secrets, backup, telemetry, logs, and sentinel work are separate observable responsibilities.",
    facts: [["Host", "northstar-prod-01", "Ready"], ["Database", "PostgreSQL 17", "Configuring"], ["Runtime", "Web + worker", "Pending"], ["Secrets", "6 references · values hidden", "Configuring"]],
    groups: [{ title: "Operational setup", items: [["Harden host", "Firewall and service account", "passed"], ["Configure database", "Volume and service", "active"], ["Install runtime", "Container runtime and units", "pending"], ["Connect logs", "Structured event intake", "pending"], ["Deploy sentinel", "Cloudflare-side observation", "pending"]] }],
    intent: "I am establishing the database before the runtime because the application contract requires migrations and durable data.",
    pi: "The order is adaptive, but each responsibility keeps an authoritative state and evidence record.",
    events: [["Configure firewall", "Only required ingress allowed", "passed"], ["Create database volume", "Volume sg-db-01 attached", "passed"], ["Start PostgreSQL", "Waiting for readiness", "active"]],
    primary: "View current activity", secondary: "Pause after current action",
    source: "Journey phase 7 behavior",
  }),
  state({
    id: "L7.3", phase: 7, name: "Operational responsibility incomplete", status: "Blocked", tone: "danger",
    objective: "Keep a material operational gap visible and tied to launch policy.",
    summary: "Database backups are configured, but no restore verification has succeeded.",
    facts: [["Backup schedule", "Daily at 02:00 UTC", "Configured"], ["Backup destination", "Cloudflare R2 · sg-backups", "Configured"], ["Latest backup", "Completed · 184 MB", "Observed"], ["Restore verification", "Not performed", "Gap"]],
    groups: [{ title: "Impact", items: [["Data protection", "Backup exists but recoverability is unproven", "risk"], ["Launch gate", "Depends on unresolved baseline policy", "unresolved"], ["Next bounded action", "Run restore verification in isolated database", "available"]] }],
    intent: "I will not describe backups as verified until a restore check produces evidence.",
    pi: "We need a product decision: does an unverified restore block the first live claim, or remain a visible accepted gap?",
    events: [["Backup completed", "Object written to R2", "passed"], ["Restore evidence check", "No successful observation found", "blocked"]],
    primary: "Run restore verification", secondary: "Record accepted gap",
    decision: "This screen intentionally does not choose whether the gap blocks launch.",
    source: "Successful outcome · Unresolved operational baseline",
  }),
  state({
    id: "L7.4", phase: 7, name: "Environment ready for Release", status: "Complete with gaps", tone: "success",
    objective: "Show whether the environment can accept a Release and what remains incomplete.",
    summary: "The environment exposes operational evidence; one accepted telemetry gap remains explicit.",
    facts: [["Runtime", "Ready for web + worker", "Verified"], ["Database", "Ready · migrations not run", "Verified"], ["Secrets", "6 references resolved", "Verified"], ["Observation path", "External sentinel active", "Verified"]],
    groups: [{ title: "Operational baseline", items: [["Backups", "Configured; restore verified", "passed"], ["Logs", "Structured intake active", "passed"], ["Telemetry", "Traces active; custom metric absent", "gap"], ["Sentinel", "External health path active", "passed"]] }],
    intent: "The environment can accept the first Release. I will carry the custom metric gap into handoff evidence.",
    pi: "This state assumes the workshop baseline allows the named telemetry gap; the final policy is still not settled.",
    events: [["Environment readiness evaluated", "All required responsibilities available", "passed"]],
    primary: "Prepare first Release",
    decision: "Illustrative outcome only: the accepted-gap threshold is not yet product policy.",
    source: "Journey phase 7 exit",
  }),

  state({
    id: "L8.1", phase: 8, name: "First Release candidate", status: "Needs review",
    objective: "Identify the exact candidate before anything is deployed.",
    summary: "Repository revision, build artifact, configuration, and migration plan form one inspectable Release candidate.",
    facts: [["Revision", "8c14d72", "GitHub main"], ["Image", "ghcr.io/northstar/web@sha256:7bf…91a", "GitHub Actions"], ["Configuration", "server-guy.yaml · digest 2b9…0cf", "Repository"], ["Migrations", "pnpm db:migrate", "Application Contract"]],
    groups: [{ title: "Eligibility", items: [["Tests", "128 passed", "passed"], ["Build", "Immutable image published", "passed"], ["Contract", "Supported profile", "passed"], ["Target", "northstar-prod-01", "ready"]] }],
    intent: "I propose deploying this exact revision and configuration as the first Release candidate.",
    pi: "Approval or autonomous action must bind to this candidate identity; a newer commit would be a different candidate.",
    events: [["Candidate selected", "Newest eligible immutable image", "recorded"]],
    primary: "Deploy first Release", secondary: "Choose another revision",
    source: "Journey phase 8 · Evidence produced",
  }),
  state({
    id: "L8.2", phase: 8, name: "Deploying", status: "Acting",
    objective: "Deploy the exact candidate and keep observations separate.",
    summary: "Build, migration, deployment, reachability, and external verification are distinct activities.",
    facts: [["Candidate", "8c14d72 · sha256:7bf…91a", "Pinned"], ["Deployment", "dep_01J...K4", "Recorded"], ["Current activity", "Starting web and worker", "Observed"], ["Public claim", "Not yet evaluated", "Authoritative"]],
    groups: [{ title: "Release activity", items: [["Pull image", "Digest matched", "passed"], ["Run migrations", "3 migrations applied", "passed"], ["Start services", "Web ready; worker starting", "active"], ["External checks", "Waiting for services", "pending"]] }],
    intent: "I am starting the pinned candidate. After reachability, I will test the intended hostname and semantic contract.",
    pi: "A successful deployment command will not be enough to call this live.",
    events: [["Apply migrations", "Schema version 20260830_03", "passed"], ["Start service", "Web process reports ready", "passed"], ["Start worker", "Waiting for heartbeat", "active"]],
    primary: "View deployment evidence", secondary: "Pause after current action",
    source: "Journey phase 8 behavior",
  }),
  state({
    id: "L8.3", phase: 8, name: "Reachable, not Verified", status: "Reachable", tone: "warning",
    objective: "Prevent reachability from being mistaken for a healthy live Release.",
    summary: "The route returns HTTP 200, but a contract-defined semantic smoke check is still failing.",
    facts: [["Hostname", "https://northstar.dev", "Reachable"], ["HTTP", "200 OK", "Observed"], ["Health contract", "Pass", "Observed"], ["Semantic smoke", "Create draft project · failed", "Verification"]],
    groups: [{ title: "Live claim", items: [["Container running", "Yes", "insufficient"], ["Public route reachable", "Yes", "insufficient"], ["Contract health", "Pass", "required"], ["Semantic verification", "Fail", "blocks claim"]] }],
    intent: "I am investigating why the application responds but the core user flow fails.",
    pi: "Reachable is not Verified. The failing draft-project check means I cannot present this candidate as healthy.",
    events: [["External GET /", "200 OK", "passed"], ["Smoke: create draft project", "500 · database permission denied", "blocked"]],
    primary: "Investigate failure", secondary: "View raw evidence",
    source: "Operator UI reachability requirement · Successful outcome",
  }),
  state({
    id: "L8.4", phase: 8, name: "Verification failed", status: "Blocked", tone: "danger",
    objective: "Diagnose adaptively without promoting a failed candidate.",
    summary: "Pi has narrowed the failure to database permissions and proposes a bounded operational correction.",
    facts: [["Candidate", "8c14d72", "Not current Release"], ["Failure", "permission denied for relation projects", "Observed"], ["Likely cause", "Migration role owns table", "Pi judgment"], ["Predecessor", "None · first launch", "Recorded"]],
    groups: [{ title: "Proposed remediation", items: [["Inspect grants", "Read-only database query", "safe"], ["Apply ownership grant", "Operational database change", "proposed"], ["Re-run smoke", "Must pass through public hostname", "required"]] }],
    intent: "I want to verify the diagnosis with read-only evidence before proposing the grant correction.",
    pi: "This appears operational rather than application-code work. If the evidence contradicts that, I will revise the plan.",
    events: [["Collect database evidence", "Application role lacks INSERT on projects", "passed"], ["Candidate health", "Rejected pending remediation", "recorded"]],
    primary: "Review remediation", secondary: "Stop launch",
    source: "Alternate path: verification fails",
  }),
  state({
    id: "L8.5", phase: 8, name: "Verified live", status: "Verified", tone: "success",
    objective: "Support the live claim with exact Release and external evidence.",
    summary: "The first Release passes contract health and Pi-selected semantic checks through the intended HTTPS hostname.",
    facts: [["Current Release", "rel_01J...Q9 · revision 8c14d72", "Recorded"], ["Hostname", "https://northstar.dev", "Verified"], ["Contract health", "3 / 3 passed", "External"], ["Semantic checks", "2 / 2 passed", "External"]],
    groups: [{ title: "Verification", items: [["DNS + HTTPS", "Valid public route", "passed"], ["Health", "Web, database, worker", "passed"], ["Smoke", "Create and read draft project", "passed"], ["Observation", "Sentinel sees healthy route", "passed"]] }],
    intent: "The exact candidate is now supported as the current live Release. I will record the handoff state and gaps.",
    pi: "This claim is based on the intended hostname and semantic behavior, not only a running container.",
    events: [["Verification suite", "All required external checks passed", "passed"], ["Release promoted", "rel_01J...Q9 marked current", "recorded"]],
    primary: "Complete launch handoff", source: "Journey phase 8 exit · Successful outcome",
  }),

  state({
    id: "L9.1", phase: 9, name: "Operational handoff overview", status: "Operational", tone: "success",
    objective: "Land the engineer in the ongoing application workspace.",
    summary: "Current Release, domain, health, cost, backups, telemetry, logs, sentinel, and recent work are visible together.",
    facts: [["Current Release", "rel_01J...Q9 · 8c14d72", "Verified"], ["Domain", "northstar.dev · HTTPS valid", "Verified"], ["Health", "Good · last observed 28s ago", "External sentinel"], ["Monthly cost", "€9.49 host + usage", "Observed"]],
    groups: [{ title: "Operational posture", items: [["Backups", "Daily · restore verified", "good"], ["Logs", "Receiving structured events", "good"], ["Telemetry", "Traces active · custom metric gap", "gap"], ["Sentinel", "External observation active", "good"]] }],
    intent: "The launch is complete. I am now observing the application and preserving the operational record.",
    pi: "The custom metric remains an explicit gap. Everything required by the current launch baseline is healthy.",
    events: [["Application Launch completed", "Release, topology, domain, and evidence recorded", "recorded"], ["Sentinel observation", "Public health check passed", "passed"]],
    primary: "Open application workspace", secondary: "Review launch evidence",
    source: "Journey phase 9",
  }),
  state({
    id: "L9.2", phase: 9, name: "Evidence and outstanding gaps", status: "Recorded",
    objective: "Keep authoritative launch evidence separate from Pi-authored notes.",
    summary: "The engineer can inspect topology, resource identities, Release evidence, and unresolved responsibilities.",
    facts: [["Topology record", "top_01J...5F", "Authoritative"], ["Launch evidence", "evb_01J...AA", "Authoritative"], ["Outstanding gaps", "1", "Authoritative"], ["Operational notes", "3 Pi-authored", "Interpretation"]],
    groups: [{ title: "Evidence bundle", items: [["Application Contract", "Fields and provenance", "recorded"], ["Provider resources", "Hetzner and Cloudflare identities", "recorded"], ["Release", "Revision, image, configuration", "recorded"], ["Verification", "External observations and semantic checks", "recorded"]] }, { title: "Outstanding gap", items: [["Custom business metric", "Accepted for launch; owner not assigned", "gap"]] }],
    intent: "I am keeping my operational interpretation next to, but distinct from, the authoritative evidence.",
    pi: "The raw evidence supports the launch claim. My note recommends adding the custom metric before capacity work begins.",
    events: [["Evidence bundle sealed", "36 observations linked to rel_01J...Q9", "recorded"]],
    primary: "Open evidence bundle", secondary: "Assign gap",
    source: "Journey phase 9 behavior · Evidence produced",
  }),
  state({
    id: "L9.3", phase: 9, name: "Ongoing application workspace", status: "Operational", tone: "success",
    objective: "Transition from launch progression to normal engineering operations.",
    summary: "The same workspace now supports ongoing observation and collaboration with Pi.",
    facts: [["Application", "northstar", "Operational"], ["Environment", "Production", "Owned"], ["Current Release", "8c14d72 · verified", "Current"], ["Observation", "Sentinel + logs + traces active", "Healthy"]],
    groups: [{ title: "Normal operations", items: [["Health", "External and application checks", "good"], ["Recent work", "Application Launch completed", "recorded"], ["Next release", "No candidate", "idle"], ["Chat", "Pi available with application context", "ready"]] }],
    intent: "I am observing northstar and can help investigate, release, or explain its operational state.",
    pi: "Launch context remains available here; you do not need to reconstruct the infrastructure or evidence in a new chat.",
    question: "Show me anything I should clean up next.",
    events: [["External observation", "https://northstar.dev/health passed", "passed"], ["Log intake", "142 structured events in the last hour", "passed"]],
    quickActions: ["Explain current health", "Show outstanding gaps", "Plan next Release"],
    primary: "View current health", secondary: "Open recent work",
    source: "Journey phase 9 exit",
  }),
];

export const statesByPhase = phases.reduce((map, phase) => {
  map[phase.id] = journeyStates.filter((item) => item.phase === phase.id);
  return map;
}, {});
