"use client";

import { ArrowRight } from "@phosphor-icons/react";

import { LinkButton, Pill, Planned, When, type ViewProps } from "./bits";

const sourceWord = {
  plan: "Deployment plan",
  user: "Provided by you",
  generated: "Generated by Server Guy",
  database: "Database connection",
  service: "Service connection",
} as const;

/**
 * Configuration is a list of names with scope and provenance; values are
 * never shown. A change that has not reached the running processes is
 * marked, and inputs Server Guy still needs point at the conversation.
 */
export function VariablesView(props: ViewProps) {
  const { deployment, facts, now, operations } = props;
  const variables = facts.variables;
  const fallback = [
    ...new Set([
      ...(deployment?.plan?.environment.map((item) => item.name) ?? []),
      ...(deployment?.plan?.missingInputs.map((item) => item.name) ?? []),
      ...(deployment?.plan?.postgres
        ? [deployment.plan.postgres.variable]
        : []),
    ]),
  ];
  if (!variables)
    return (
      <>
        {fallback.length ? (
          <div className="sg-variable-list">
            <div className="sg-variable-row sg-table-head">
              <span>Name</span>
              <span>Value</span>
            </div>
            {fallback.map((name) => (
              <div className="sg-variable-row" key={name}>
                <code>{name}</code>
                <span>Hidden</span>
              </div>
            ))}
          </div>
        ) : (
          <div className="sg-section-empty">
            <h2>No variables recorded</h2>
            <p>
              Required configuration will appear after repository inspection.
            </p>
          </div>
        )}
        <p className="sg-section-note">
          Names come from the deployment plan. Secret values are never exposed
          in this view.
        </p>
        <Planned title="Configuration with a clear impact">
          Editing, rotating secrets, and distinguishing build-time from runtime
          values will live here. Missing deployment inputs are provided in the
          deployment approval inside the conversation.
        </Planned>
      </>
    );
  const pendingRestart = variables.variables.filter(
    (item) => item.pendingRestart,
  );
  return (
    <>
      {variables.pending.length > 0 && (
        <div className="sg-pending-inputs">
          <strong>
            Waiting for {variables.pending.length} value
            {variables.pending.length === 1 ? "" : "s"}
          </strong>
          <ul>
            {variables.pending.map((item) => {
              const operation = operations.find(
                (candidate) => candidate.id === item.operationId,
              );
              return (
                <li key={item.name}>
                  <code>{item.name}</code> · {item.reason}
                  {operation?.origin && (
                    <LinkButton
                      onClick={() =>
                        props.onOpenConversation(
                          operation.origin!.chatId,
                          operation.origin!.messageId,
                        )
                      }
                    >
                      Provide in the conversation{" "}
                      <ArrowRight aria-hidden="true" />
                    </LinkButton>
                  )}
                </li>
              );
            })}
          </ul>
        </div>
      )}
      {pendingRestart.length > 0 && (
        <p className="sg-op-next">
          {pendingRestart.length} change
          {pendingRestart.length === 1 ? "" : "s"} will reach the running
          processes with the next release or restart.
        </p>
      )}
      <div className="sg-variable-list sg-variable-list-wide">
        <div className="sg-variable-row sg-table-head">
          <span>Name</span>
          <span>Scope</span>
          <span>Source</span>
          <span>Value</span>
        </div>
        {variables.variables.map((item) => (
          <div className="sg-variable-row" key={item.name}>
            <span>
              <code>{item.name}</code>
              {item.note && <small>{item.note}</small>}
            </span>
            <span>
              {item.scope === "both"
                ? "Build and runtime"
                : item.scope === "build"
                  ? "Build"
                  : "Runtime"}
            </span>
            <span>{sourceWord[item.source]}</span>
            <span>
              {item.secret ? "Hidden" : "Visible to the application"}
              {item.updatedAt && (
                <small>
                  updated <When at={item.updatedAt} now={now} />
                </small>
              )}
              {item.pendingRestart && <Pill tone="warn">Restart pending</Pill>}
            </span>
          </div>
        ))}
      </div>
      <p className="sg-section-note">
        Values reach only the processes that need them and never appear here.
        Ask in a conversation to add, change or rotate one; Server Guy applies
        it and says whether a restart or release is needed.
      </p>
    </>
  );
}
