"use client";

import { ArrowRight } from "@phosphor-icons/react";

import {
  Condition,
  LinkButton,
  Pill,
  Planned,
  When,
  type ViewProps,
} from "./bits";

/** Provenance is the axis that matters: who decided this value. */
const groups = [
  {
    key: "user",
    title: "Provided by you",
    note: "Secrets you supplied when approving work.",
  },
  {
    key: "generated",
    title: "Generated by Server Guy",
    note: "Created during deployment and never shown.",
  },
  {
    key: "database",
    title: "Connections",
    note: "Wired to the private services in this stack.",
  },
  {
    key: "service",
    title: "Connections",
    note: "Wired to the private services in this stack.",
  },
  {
    key: "plan",
    title: "From the deployment plan",
    note: "Read from the repository at the recorded revision.",
  },
] as const;

/**
 * Configuration is a list of names with scope and provenance; values are
 * never shown. A change that has not reached the running processes is
 * marked, and inputs Server Guy still needs point at the conversation.
 */
export function VariablesView(props: ViewProps) {
  const { deployment, facts, now, operations } = props;
  const variables = facts.variables;
  const fallback = [
    ...new Set([
      ...(deployment?.plan?.environment.map((item) => item.name) ?? []),
      ...(deployment?.plan?.missingInputs.map((item) => item.name) ?? []),
      ...(deployment?.plan?.postgres
        ? [deployment.plan.postgres.variable]
        : []),
    ]),
  ];
  if (!variables)
    return (
      <>
        {fallback.length ? (
          <>
            <Condition tone="muted" title={`${fallback.length} names recorded`}>
              These come from the deployment plan at the recorded revision.
              Values are held on the host and never shown here.
            </Condition>
            <ul
              className="sg-variable-names"
              aria-label="Recorded variable names"
            >
              {fallback.map((name) => (
                <li key={name}>
                  <code>{name}</code>
                </li>
              ))}
            </ul>
          </>
        ) : (
          <div className="sg-section-empty">
            <h2>No variables recorded</h2>
            <p>
              Required configuration will appear after repository inspection.
            </p>
          </div>
        )}
        <Planned title="Configuration with a clear impact">
          Editing, rotating secrets, and distinguishing build-time from runtime
          values will live here. Missing deployment inputs are provided in the
          deployment approval inside the conversation.
        </Planned>
      </>
    );
  const pendingRestart = variables.variables.filter(
    (item) => item.pendingRestart,
  );
  const seen = new Set<string>();
  const sections = groups
    .filter((group) => {
      if (seen.has(group.title)) return false;
      seen.add(group.title);
      return true;
    })
    .map((group) => ({
      ...group,
      items: variables.variables.filter((item) =>
        group.title === "Connections"
          ? item.source === "database" || item.source === "service"
          : item.source === group.key,
      ),
    }))
    .filter((group) => group.items.length);
  return (
    <>
      <Condition
        tone={
          variables.pending.length
            ? "warn"
            : pendingRestart.length
              ? "warn"
              : "ok"
        }
        title={
          variables.pending.length
            ? `Waiting for ${variables.pending.length} value${variables.pending.length === 1 ? "" : "s"}`
            : pendingRestart.length
              ? `${pendingRestart.length} change${pendingRestart.length === 1 ? "" : "s"} not live yet`
              : `${variables.variables.length} variables · all applied`
        }
      >
        {variables.pending.length
          ? "Server Guy cannot continue until these are provided in the conversation that asked for them."
          : pendingRestart.length
            ? "The change is recorded; it reaches the running processes with the next release or restart."
            : "Every recorded value has reached the processes that need it. Values never appear in this view."}
      </Condition>
      {variables.pending.length > 0 && (
        <div className="sg-pending-inputs">
          <ul>
            {variables.pending.map((item) => {
              const operation = operations.find(
                (candidate) => candidate.id === item.operationId,
              );
              return (
                <li key={item.name}>
                  <code>{item.name}</code> · {item.reason}
                  {operation?.origin && (
                    <LinkButton
                      onClick={() =>
                        props.onOpenConversation(
                          operation.origin!.chatId,
                          operation.origin!.messageId,
                        )
                      }
                    >
                      Provide in the conversation{" "}
                      <ArrowRight aria-hidden="true" />
                    </LinkButton>
                  )}
                </li>
              );
            })}
          </ul>
        </div>
      )}
      {sections.map((group) => (
        <div className="sg-band" key={group.title}>
          <div className="sg-band-head">
            <h2>{group.title}</h2>
            <span className="sg-visual-caption">{group.note}</span>
          </div>
          <div className="sg-variable-list sg-variable-list-grouped">
            <div className="sg-variable-row sg-table-head">
              <span>Name</span>
              <span>Scope</span>
              <span>Value</span>
            </div>
            {group.items.map((item) => (
              <div
                className={`sg-variable-row${item.pendingRestart ? " sg-row-warn" : ""}`}
                key={item.name}
              >
                <span>
                  <code>{item.name}</code>
                  {item.note && <small>{item.note}</small>}
                </span>
                <span>
                  {item.scope === "both"
                    ? "Build and runtime"
                    : item.scope === "build"
                      ? "Build"
                      : "Runtime"}
                </span>
                <span>
                  {item.secret ? "Hidden" : "Visible to the application"}
                  {item.updatedAt && (
                    <small>
                      updated <When at={item.updatedAt} now={now} />
                    </small>
                  )}
                  {item.pendingRestart && (
                    <Pill tone="warn">Restart pending</Pill>
                  )}
                </span>
              </div>
            ))}
          </div>
        </div>
      ))}
      <p className="sg-section-note">
        Values reach only the processes that need them and never appear here.
        Ask in a conversation to add, change or rotate one; Server Guy applies
        it and says whether a restart or release is needed.
      </p>
    </>
  );
}
