const launchNodes = [
  {
    id: "inspect",
    number: "01",
    short: "Inspect",
    title: "Inspect repository",
    kind: "deterministic",
    owner: "Server Guy",
    effect: "Read-only",
    dependencies: "Repository access",
    summary: "Read the repository, detect the supported profile, and capture source-backed facts.",
    evidence: "Repository snapshot · commit 8b72a41",
  },
  {
    id: "contract",
    number: "02",
    short: "Contract",
    title: "Resolve application contract",
    kind: "deterministic",
    owner: "Server Guy",
    effect: "Repository proposal",
    dependencies: "Repository inspection",
    summary: "Compare required profile fields with repository facts and produce the smallest explicit contract delta.",
    evidence: "Next.js + PostgreSQL profile v0.1",
  },
  {
    id: "vps",
    number: "03",
    short: "VPS",
    title: "Reconcile compute",
    kind: "deterministic",
    owner: "Hetzner adapter",
    effect: "Paid provider write",
    dependencies: "Accepted plan · provider credential",
    summary: "Create or import the intended server, then verify the provider receipt and SSH reachability.",
    evidence: "Hetzner request plan · cx32 / fsn1",
  },
  {
    id: "dns",
    number: "04",
    short: "Domain",
    title: "Reconcile public route",
    kind: "deterministic",
    owner: "Cloudflare adapter",
    effect: "DNS write",
    dependencies: "Reachable host · hostname",
    summary: "Make the intended hostname route to the verified host and wait for external resolution.",
    evidence: "Cloudflare zone northstar.dev",
  },
  {
    id: "runtime",
    number: "05",
    short: "Runtime",
    title: "Reconcile runtime",
    kind: "deterministic",
    owner: "Host runner",
    effect: "Server configuration",
    dependencies: "Reachable host · application contract",
    summary: "Install the pinned runtime, configure services, secrets, storage, and process supervision.",
    evidence: "Runtime plan · Caddy + app + PostgreSQL",
  },
  {
    id: "release",
    number: "06",
    short: "Release",
    title: "Apply release",
    kind: "deterministic",
    owner: "Release runner",
    effect: "Production mutation",
    dependencies: "Runtime ready · release identity",
    summary: "Build and start one identified release without silently changing the application contract.",
    evidence: "Release 9f3c2ad · production",
  },
  {
    id: "verify",
    number: "07",
    short: "Verify",
    title: "Verify from outside",
    kind: "deterministic",
    owner: "Verification runner",
    effect: "Read-only",
    dependencies: "Release started · public route",
    summary: "Run contract-defined probes from outside the host and compare the observed release with the intended release.",
    evidence: "HTTP, TLS, health, database and release probes",
  },
  {
    id: "evidence",
    number: "08",
    short: "Evidence",
    title: "Assemble launch evidence",
    kind: "deterministic",
    owner: "Evidence store",
    effect: "Record append",
    dependencies: "Fresh provider and verification observations",
    summary: "Bind claims to receipts, observations, revisions, and timestamps so the launch can be inspected later.",
    evidence: "Immutable launch bundle launch_01J8M3",
  },
];

function graph(statuses, overrides = {}) {
  return launchNodes.map((node) => ({
    ...node,
    status: statuses[node.id] || "queued",
    ...(overrides[node.id] || {}),
  }));
}

export const reconciliationScenarios = {
  input: {
    id: "input",
    number: "01",
    label: "Input / Decision",
    phase: 4,
    state: "L4.1",
    deliverable: "Launch Plan",
    status: "Needs input",
    headline: "One desired-state choice is unresolved",
    piCopy: "I inspected the repository and provider connections. The normal launch procedure is known, but two valid hostnames remain. I need a product choice before the planner can produce one executable graph.",
    objective: "Resolve the production hostname, then recompute the launch plan.",
    desired: [
      ["Profile", "Next.js + PostgreSQL v0.1", "Application Contract"],
      ["Environment", "Production", "Decision from chat"],
      ["Public hostname", "Unresolved", "Needs operator intent"],
    ],
    observed: [
      ["Repository", "Conformant", "commit 8b72a41"],
      ["Cloudflare zone", "northstar.dev connected", "provider read"],
      ["Available routes", "apex and app subdomain", "DNS observation"],
    ],
    deltas: [
      ["decision", "Choose one production hostname", "blocks Domain node"],
      ["create", "Create Hetzner CX32", "planned after approval"],
      ["configure", "Create runtime and release", "planned"],
    ],
    selectedNodeId: "contract",
    judgment: {
      nodeId: "contract",
      title: "Hostname intent cannot be inferred safely",
      reason: "Both routes satisfy the technical contract. Choosing the apex affects future product and marketing use, so this is a user-owned product decision rather than an infrastructure default.",
      options: ["Use app.northstar.dev", "Use northstar.dev"],
    },
    nodes: graph(
      { inspect: "done", contract: "needs-input" },
      { contract: { kind: "judgment", owner: "Pi with operator", effect: "Decision Record only", summary: "Pi frames the trade-off; the user owns the hostname choice. The deterministic planner resumes from the recorded decision." } },
    ),
  },
  review: {
    id: "review",
    number: "02",
    label: "Review / Proposal",
    phase: 4,
    state: "L4.2",
    deliverable: "Launch Plan",
    status: "Awaiting review",
    headline: "Desired and actual state produce eight operations",
    piCopy: "The hostname decision closed the only ambiguity. Server Guy recomputed a dependency-ordered launch graph. I highlighted the paid resource, production mutation, and one unresolved backup destination for review.",
    objective: "Understand the concrete effects before allowing reconciliation to begin.",
    desired: [
      ["Hostname", "app.northstar.dev", "Decision record"],
      ["Compute", "CX32 · fsn1 · Ubuntu 24.04", "Launch contract"],
      ["Cost ceiling", "€12 / month", "Decision from chat"],
    ],
    observed: [
      ["Hetzner server", "Not found", "provider read"],
      ["DNS route", "Not found", "authoritative lookup"],
      ["Release", "Not deployed", "host observation"],
    ],
    deltas: [
      ["create", "One Hetzner CX32", "paid external effect"],
      ["write", "Cloudflare A record", "DNS external effect"],
      ["apply", "Runtime + release + verification", "host changes"],
    ],
    selectedNodeId: "vps",
    nodes: graph({ inspect: "done", contract: "done", vps: "planned", dns: "planned", runtime: "planned", release: "planned", verify: "planned", evidence: "planned" }),
  },
  approval: {
    id: "approval",
    number: "03",
    label: "Approval",
    phase: 5,
    state: "L5.2",
    deliverable: "VPS Provisioning",
    status: "Approval required",
    headline: "The next deterministic operation starts billing",
    piCopy: "The graph is ready to apply. The next node creates a paid Hetzner resource, so Server Guy is paused at the approval boundary configured for this session.",
    objective: "Approve, change, or cancel the exact compute operation.",
    desired: [
      ["Server", "CX32 · fsn1", "Accepted launch plan"],
      ["Image", "Ubuntu 24.04", "Profile default"],
      ["Budget", "≤ €12 / month", "Decision record"],
    ],
    observed: [
      ["Matching server", "None", "Hetzner inventory read"],
      ["Current monthly spend", "€0", "provider account"],
      ["Scoped credential", "Connected", "credential store"],
    ],
    deltas: [["create", "server northstar-prod-01", "billing begins on provider acceptance"]],
    selectedNodeId: "vps",
    approval: {
      nodeId: "vps",
      title: "Create Hetzner CX32",
      boundary: "Maximum €12/month · one server · fsn1",
      consequence: "Billing begins when Hetzner accepts the request. Later graph nodes remain independently observable and stoppable.",
    },
    nodes: graph({ inspect: "done", contract: "done", vps: "approval", dns: "queued", runtime: "queued", release: "queued", verify: "queued", evidence: "queued" }),
  },
  operation: {
    id: "operation",
    number: "04",
    label: "Operation",
    phase: 6,
    state: "L6.5",
    deliverable: "Domain Route",
    status: "Reconciling",
    headline: "DNS write completed; verification is waiting on reality",
    piCopy: "Cloudflare accepted the intended A record. Server Guy is now observing authoritative and public resolvers. It will not resubmit the write while propagation is incomplete.",
    objective: "Observe the submitted change until the public route matches the contract.",
    desired: [
      ["A record", "app → 203.0.113.42", "Launch contract"],
      ["Proxy mode", "DNS only during verification", "Profile rule"],
      ["TLS target", "Caddy on northstar-prod-01", "Runtime plan"],
    ],
    observed: [
      ["Cloudflare", "Change accepted", "receipt cf_req_9f21"],
      ["1.1.1.1", "203.0.113.42", "10:31:18 UTC"],
      ["8.8.8.8", "Previous target cached", "10:31:22 UTC"],
    ],
    deltas: [["wait", "Public resolvers converge", "no additional provider write"]],
    selectedNodeId: "dns",
    nodes: graph({ inspect: "done", contract: "done", vps: "done", dns: "running", runtime: "queued", release: "queued", verify: "queued", evidence: "queued" }),
  },
  intervention: {
    id: "intervention",
    number: "05",
    label: "Intervention",
    phase: 6,
    state: "L6.6",
    deliverable: "Domain Route",
    status: "Blocked",
    headline: "Observed DNS state has an unexplained owner",
    piCopy: "The deterministic DNS node stopped because an existing AAAA record sends IPv6 clients elsewhere. I correlated provider state and external probes, but the evidence does not identify whether that route is stale or intentionally owned.",
    objective: "Resolve ownership of the conflicting record, then recompute the DNS operation.",
    desired: [
      ["Public route", "All clients reach northstar-prod-01", "Application Contract"],
      ["IPv4", "203.0.113.42", "Host record"],
      ["IPv6", "No requirement", "Profile v0.1"],
    ],
    observed: [
      ["A", "203.0.113.42", "matches intended host"],
      ["AAAA", "2001:db8:42::7", "unknown prior target"],
      ["IPv6 probe", "502", "external observation"],
    ],
    deltas: [["blocked", "AAAA ownership must be resolved", "destructive overwrite refused"]],
    selectedNodeId: "dns",
    judgment: {
      nodeId: "dns",
      title: "Pi must resolve intent, not invent it",
      reason: "The technical facts show a conflict, but not whether another service owns the IPv6 address. Pi can investigate history and explain options; the resulting desired state is then re-planned deterministically.",
      options: ["Remove stale AAAA", "Preserve IPv6 and configure the host"],
    },
    nodes: graph(
      { inspect: "done", contract: "done", vps: "done", dns: "blocked", runtime: "queued", release: "queued", verify: "queued", evidence: "queued" },
      { dns: { kind: "judgment", owner: "Pi with operator", effect: "No write while intent is unknown", summary: "The provider adapter detected conflicting state and stopped. Pi investigates ownership; Server Guy applies only the resulting reconciled plan." } },
    ),
  },
  outcome: {
    id: "outcome",
    number: "06",
    label: "Outcome",
    phase: 8,
    state: "L8.5",
    deliverable: "Verified Release",
    status: "Healthy",
    headline: "Observed production state matches the launch contract",
    piCopy: "Every required graph node completed and fresh external observations support the verified-release claim. The application-specific business metric remains an explicit accepted gap.",
    objective: "Inspect the proof, open the application, or change the desired state and reconcile again.",
    desired: [
      ["Release", "9f3c2ad", "main branch"],
      ["Hostname", "app.northstar.dev", "Decision record"],
      ["Health", "Contract checks pass", "Application Contract"],
    ],
    observed: [
      ["HTTP / TLS", "200 · valid certificate", "public probe"],
      ["Release", "9f3c2ad", "/health response"],
      ["Database", "Read/write passed", "application probe"],
    ],
    deltas: [["none", "No launch drift detected", "verified 10:42:18 UTC"]],
    selectedNodeId: "verify",
    claims: [
      ["Production route serves Release 9f3c2ad", "HTTP + release identity observations"],
      ["TLS is valid for app.northstar.dev", "certificate probe artifact"],
      ["Required health contract passes", "health + database observations"],
    ],
    nodes: graph({ inspect: "done", contract: "done", vps: "done", dns: "done", runtime: "done", release: "done", verify: "done", evidence: "done" }),
  },
  handoff: {
    id: "handoff",
    number: "07",
    label: "Agent Handoff",
    phase: 3,
    state: "L3.W3",
    deliverable: "Conformance Result",
    status: "Awaiting review",
    headline: "A repository gap became a bounded coding task",
    piCopy: "The profile check found no production health endpoint. Server Guy assembled a scoped handoff with the contract, failing check, and repository evidence. The coding worker returned Pull Request #42; the launch graph stays paused until conformance is verified.",
    objective: "Review the code change and re-run the deterministic profile check.",
    desired: [
      ["Health endpoint", "GET /health", "Profile requirement"],
      ["Response", "release + dependency state", "Application Contract"],
      ["Repository", "No unrelated app changes", "Handoff scope"],
    ],
    observed: [
      ["Current main", "No /health route", "repository inspection"],
      ["Pull Request", "#42 · 3 files", "GitHub"],
      ["CI", "Lint, tests, build passed", "GitHub Actions"],
    ],
    deltas: [["review", "Merge PR #42 after profile smoke check", "repository change"]],
    selectedNodeId: "contract",
    handoff: {
      title: "Pull Request #42 · health endpoint",
      scope: "3 files · +78 −1 · feature/health-endpoint",
      checks: "Lint passed · tests passed · build passed · profile smoke pending",
    },
    nodes: graph(
      { inspect: "done", contract: "blocked", vps: "queued", dns: "queued", runtime: "queued", release: "queued", verify: "queued", evidence: "queued" },
      { contract: { kind: "external-agent", title: "Restore profile conformance", owner: "Coding agent via GitHub", effect: "Reviewable pull request", summary: "Server Guy supplies the exact failed contract check and evidence. The coding agent changes application code; Server Guy re-runs conformance before the launch graph resumes.", evidence: "Pull Request #42 · commit 9f3c2ad" } },
    ),
  },
};

export const families = Object.values(reconciliationScenarios).map(({ nodes, desired, observed, deltas, piCopy, objective, headline, judgment, approval, claims, handoff, selectedNodeId, ...family }) => family);

export function getScenario(id) {
  return reconciliationScenarios[id] || reconciliationScenarios.input;
}
